### PR TITLE
Use dd.read_csv to get metadata to avoid reading large files

### PR DESCRIPTION
**Pull request by VibhuJawa**
Fixes https://github.com/rapidsai/dask-cudf/issues/144. 

- [ ] add change_log

### CODE REVIEW

**Comment by mrocklin** [comment]
In principle this seems fine to me.

It's unfortunate that CI has broken, so it's hard to determine if this breaks anything else.  I'm going to try the rerun tests bit to see if I have sufficient permissions here.

**Comment by mrocklin** [comment]
rerun tests

**Comment by quasiben** [comment]
we also need the changelog updated here

**Comment by mrocklin** [comment]
> we also need the changelog updated here

No we don't.  I update the changelog for dask-cudf manually on release time.

**Comment by quasiben** [comment]
Oh I was thinking of cudf, sorry.

**Comment by VibhuJawa** [comment]
rerun tests

**Comment by mrocklin** [comment]
rerun tests

**Comment by VibhuJawa** [comment]
rerun tests

**Pull request merged**
