### PR TITLE
Use mainline groupby aggregation codebase

### PR DESCRIPTION
**Pull request by mrocklin**
This will require some effort within cudf to make this work.

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @kkraus14 @thomcom in case you want to get broader context on what I'm trying.  It would be good if the following would pass

```
py.test dask_cudf/tests/test_groupby
```

This is currently pretty small, but should be a good driver for the cudf groupby fixes.

**Comment by thomcom** [comment]
First steps made in https://github.com/rapidsai/cudf/pull/878. I'll be adding MultiIndex and MultiColumn as soon as possible.

**Comment by mrocklin** [comment]
Thanks @thomcom just to be clear we only need MultiIndex on the columns, not on the rows.  Hopefully that helps to keep scope small and progress fast :)

I also cced you on a couple other small issues that arose when trying out this test suite on your recent work.

**Comment by mrocklin** [comment]
Thanks to work by @thomcom on cudf we can now do the following:

```
```In [1]: import dask, cudf

In [2]: df = dask.datasets.timeseries(dtypes={'x': int, 'y': float}).reset_index(drop=True)

In [3]: df['x'] = df.x % 10

In [4]: df.head()
Out[4]:
   x         y
0  3 -0.882867
1  1  0.130764
2  2  0.625918
3  3  0.322409
4  6 -0.078021

In [5]: gdf = df.map_partitions(cudf.from_pandas)

In [6]: gdf.groupby('x')[['y']].sum().compute().to_pandas()
Out[6]:
            y
0  291.887231
1 -121.165475
2    8.630158
3  319.097651
4 -261.517349
5 -123.051868
6 -306.819297
7   92.280398
8 -225.310512
9  212.983393
```

That example is a bit fragile at the moment, making it marginally more complex breaks things, but something works!

**Comment by mrocklin** [comment]
@thomcom I've added back in the std tests

**Comment by mrocklin** [comment]
@randerzander we're at a point where getting more information about the specific kinds of groupbys that interest you would be helpful.

**Comment by mrocklin** [comment]
Thought I'd point out that many things currently work.  The std and agg functions still don't though.

```python
In [1]: import cudf, dask
   ...: df = dask.datasets.timeseries(dtypes={'x': int, 'y': float}).reset_index(drop=True)
   ...: df['x'] = df.x % 10
   ...: gdf = df.map_partitions(cudf.from_pandas)
   ...:
   ...:

In [2]: gdf.groupby('x')[['y']].sum().compute().to_pandas()
Out[2]:
            y
0   -9.197062
1  407.398753
2 -153.444847
3  -55.538811
4  278.789062
5 -488.075452
6 -412.039540
7  -17.670441
8 -184.553159
9  183.175555

In [3]: gdf.groupby('x')[['y']].mean().compute().to_pandas()
Out[3]:
          y
0 -0.000036
1  0.001574
2 -0.000592
3 -0.000214
4  0.001077
5 -0.001881
6 -0.001590
7 -0.000068
8 -0.000711
9  0.000707

In [4]: gdf.groupby('x')[['y']].max().compute().to_pandas()
Out[4]:
          y
0  0.999998
1  0.999987
2  0.999989
3  0.999984
4  0.999980
5  0.999989
6  0.999994
7  0.999996
8  1.000000
9  0.999990
```

**Comment by mrocklin** [comment]
I've merged this in for now.  The functionality is better than what was in master.  We would still like to be able to un-xfail the std and agg tests though.

**Pull request merged**
